Update rakpios-cli-install

diff --git a/rakpios-cli-install b/rakpios-cli-install
--- a/rakpios-cli-install
+++ b/rakpios-cli-install
@@ -67,21 +67,30 @@ main(){
 do_check_install_status(){
     if [ -d "$DIR" ]; then
         echo "Looks like rakpios-cli is already installed in "$DIR"..."
-        read -p "Do you want to upgrade the rakpios-cli to the latest version (y/n)?" choice
-        case "$choice" in 
-            y|Y ) 
-                echo "Start to upgrade..."
-                do_upgrade
-                ;;
-            n|N ) 
-                echo "Cancel upgrade, exiting now..."
-                exit 1
-                ;;
-            * ) 
-                echo "Invalid option, exiting now..."
-                exit 1
-                ;;
-        esac
+        whiptail --title "Confirmation" --yesno "Do you want to upgrade the rakpios-cli to the latest version (y/n)?" 8 78 --yes-button "Upgrade" --no-button "Exit" 
+        if [[ $? -eq 0 ]]; then 
+            do_upgrade
+            # docker rm udp-packet-forwarder
+            # whiptail --title "MESSAGE" --msgbox "The container named udp-packet-forwarder is stopped and removed." 8 78 
+        elif [[ $? -eq 1 ]]; then 
+            whiptail --title "MESSAGE" --msgbox "Cancelling Process since user pressed <EXIT>." 8 78
+            exit 0
+
+        # read "Do you want to upgrade the rakpios-cli to the latest version (y/n)?" choice
+        # case "$choice" in 
+        #     y|Y ) 
+        #         echo "Start to upgrade..."
+        #         do_upgrade
+        #         ;;
+        #     n|N ) 
+        #         echo "Cancel upgrade, exiting now..."
+        #         exit 1
+        #         ;;
+        #     * ) 
+        #         echo "Invalid option, exiting now..."
+        #         exit 1
+        #         ;;
+        # esac
     else
         do_fresh_install
         exit 0
